[package]
name = "git-cdiff"
version = "0.1.0"
edition = "2021"
authors = ["Dylan Palmieri <dgpalmieri@gmail.com>"]
description = "Explore differences over a set of Conventional Commits"

[dependencies]
git2 = "0.19.0"
thiserror = "1.0.66"
